### ISSUE TITLE
Le create super user ne veut pas se cree

### ISSUE THREAD

**Issue by Ethan081** [EcoleNumeriqueVivant/Shamengo#5]
Bonjour,
Lorsque je veus cree le super user . je cree un models. Je fais ma makemigration, le tableau de mon model est bien cree. je fais la migration.il prend bien en compte l application cree. 
Mais lors de la creation du super user: Message suivant: 

`Traceback (most recent call last):
  File "/home/zetp/code/Ethan081/EcoleNumVivant/myenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 197, in fetch_command
    app_name = commands[subcommand]
KeyError: 'createsuperuser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/zetp/code/Ethan081/EcoleNumVivant/myenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/zetp/code/Ethan081/EcoleNumVivant/myenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/zetp/code/Ethan081/EcoleNumVivant/myenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 204, in fetch_command
    settings.INSTALLED_APPS
  File "/home/zetp/code/Ethan081/EcoleNumVivant/myenv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/zetp/code/Ethan081/EcoleNumVivant/myenv/lib/python3.5/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/zetp/code/Ethan081/EcoleNumVivant/myenv/lib/python3.5/site-packages/django/conf/__init__.py", line 125, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
`
Pourquoi une KeyError : 'superUser'?
"The SECRET_KEY setting must not be empty." J ai bien une champ secret key dans mes settings. qui est presente.
Merci de m eclairer.
Bonne soiree ou journee.

**Comment by Hubertmaie** [comment]
Je pense savoir d ou vient ton probleme.
Il faut lancer les 2 1ere commandes du make file a chaque fois dans chaque fenetre de commandes. Je pense que c pas trop normal et qu il faudrait integrer ces 2 lignes quelques part mais je sais pas ou...

Est ce que ca marche?

DJANGO_SETTINGS_MODULE:=shamengo.settings.dev

export DJANGO_SETTINGS_MODULE

**Comment by Ethan081** [comment]
Hello, 
De se que j'ai compris le 'export DJANGO_SETTINGS_MODULE' est juste la pour indiquer d utiliser le fichier dev dans le dossier settings. j ai fais un environement virtuelle tout installer a l interieur.
je continue mes recherche.

**Comment by Hubertmaie** [comment]
moi ca avait debloque cette erreur. Mais elle revient si je ne relance pas ces 2 lignes..

**Comment by Ethan081** [comment]
Quant tu dit "Il faut lancer les 2 1ere commandes du make file a chaque fois dans chaque fenetre de commandes" c est  : DJANGO_SETTINGS_MODULE:=shamengo.settings.dev, export DJANGO_SETTINGS_MODULE ?
Comment tu les lances? Dans le terminal?
Merci.

**Comment by Hubertmaie** [comment]
Oui dans le terminal ! Je le fais dans le terminal ou je lance le serveur + le 2eme terminal de 'travail' et je dois le refaire a chaque fois

**Comment by Ethan081** [comment]
J ai essayer toujours la meme erreur. Quant je lance un server il m indique bien` 'Django version 2.0.4, using settings 'shamengo.settings.dev'`
mais pour la crea du superUser Toujoutrs l erreur :`
  ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
`

**Comment by Ethan081** [comment]
C est bon c est resolu. Cree le super User par le shell comme dans la video du 20/4/18.
merci de votre aide.
